### ISSUE TITLE
Allow new cache debug logging to be disabled

### ISSUE THREAD

**Issue by gamort** [magento/magento-cloud-components#46]
**Is your feature request related to a problem? Please describe.**
After upgrading the magento cloud extensions yesterday, my staging server generated a 1.7 GB file yesterday.
This very very quickly eats up disk space.

**Describe the solution you'd like**
Add an option in the admin to adjust the backtrace.  Disable it or limit the number of lines of backtrace.

**Describe alternatives you've considered**
Just add an option to disable it

**Comment by YPyltiai** [comment]
@shiftedreality , @Alkar778 , wasn't that fixed already?

**Comment by Alkar778** [comment]
There is a partial solution developed which decrease the number of logs 
https://github.com/magento/magento-cloud-components/pull/40

For the complete solution SWAT still working on it
